// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: driverpb/driver.proto

// Package weft.driver.v1 is the wire contract for the weft driver go-plugin
// transport. Each of the four driver interfaces in github.com/openweft/
// weft-drivers (HypervisorDriver, NetworkDriver, VolumeDriver, ImageDriver)
// maps to one gRPC service here, one RPC per interface method. All four are
// served by a single plugin process (one per host) and dispensed to the host
// as a DriverSet — see ../plugin.go.
//
// The messages mirror weft-drivers/types.go exactly. Those structs were
// designed flat + primitive-valued precisely so this mapping is mechanical:
// no nested maps, no pointers, no time.Time on the wire.

package driverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Az            string                 `protobuf:"bytes,3,opt,name=az,proto3" json:"az,omitempty"`
	Hypervisor    string                 `protobuf:"bytes,4,opt,name=hypervisor,proto3" json:"hypervisor,omitempty"`
	Architecture  string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_driverpb_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{0}
}

func (x *HostInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetAz() string {
	if x != nil {
		return x.Az
	}
	return ""
}

func (x *HostInfo) GetHypervisor() string {
	if x != nil {
		return x.Hypervisor
	}
	return ""
}

func (x *HostInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type HostInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostInfo      *HostInfo              `protobuf:"bytes,1,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfoResponse) Reset() {
	*x = HostInfoResponse{}
	mi := &file_driverpb_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoResponse) ProtoMessage() {}

func (x *HostInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoResponse.ProtoReflect.Descriptor instead.
func (*HostInfoResponse) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{1}
}

func (x *HostInfoResponse) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

type VMSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ProjectUuid   string                 `protobuf:"bytes,2,opt,name=project_uuid,json=projectUuid,proto3" json:"project_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CpuCount      int32                  `protobuf:"varint,4,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryMib     int32                  `protobuf:"varint,5,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	BootKind      string                 `protobuf:"bytes,6,opt,name=boot_kind,json=bootKind,proto3" json:"boot_kind,omitempty"`
	BootRef       string                 `protobuf:"bytes,7,opt,name=boot_ref,json=bootRef,proto3" json:"boot_ref,omitempty"`
	Cmdline       string                 `protobuf:"bytes,8,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMSpec) Reset() {
	*x = VMSpec{}
	mi := &file_driverpb_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMSpec) ProtoMessage() {}

func (x *VMSpec) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMSpec.ProtoReflect.Descriptor instead.
func (*VMSpec) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{2}
}

func (x *VMSpec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VMSpec) GetProjectUuid() string {
	if x != nil {
		return x.ProjectUuid
	}
	return ""
}

func (x *VMSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMSpec) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *VMSpec) GetMemoryMib() int32 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *VMSpec) GetBootKind() string {
	if x != nil {
		return x.BootKind
	}
	return ""
}

func (x *VMSpec) GetBootRef() string {
	if x != nil {
		return x.BootRef
	}
	return ""
}

func (x *VMSpec) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

type DiskSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeUuid    string                 `protobuf:"bytes,1,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	BackingPath   string                 `protobuf:"bytes,2,opt,name=backing_path,json=backingPath,proto3" json:"backing_path,omitempty"`
	Bus           string                 `protobuf:"bytes,3,opt,name=bus,proto3" json:"bus,omitempty"`
	SizeGib       int32                  `protobuf:"varint,4,opt,name=size_gib,json=sizeGib,proto3" json:"size_gib,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Boot          bool                   `protobuf:"varint,6,opt,name=boot,proto3" json:"boot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskSpec) Reset() {
	*x = DiskSpec{}
	mi := &file_driverpb_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSpec) ProtoMessage() {}

func (x *DiskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSpec.ProtoReflect.Descriptor instead.
func (*DiskSpec) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{3}
}

func (x *DiskSpec) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *DiskSpec) GetBackingPath() string {
	if x != nil {
		return x.BackingPath
	}
	return ""
}

func (x *DiskSpec) GetBus() string {
	if x != nil {
		return x.Bus
	}
	return ""
}

func (x *DiskSpec) GetSizeGib() int32 {
	if x != nil {
		return x.SizeGib
	}
	return 0
}

func (x *DiskSpec) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *DiskSpec) GetBoot() bool {
	if x != nil {
		return x.Boot
	}
	return false
}

type NICHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NICHandle) Reset() {
	*x = NICHandle{}
	mi := &file_driverpb_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NICHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NICHandle) ProtoMessage() {}

func (x *NICHandle) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NICHandle.ProtoReflect.Descriptor instead.
func (*NICHandle) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{4}
}

func (x *NICHandle) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NICHandle) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type NetworkSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uuid           string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ProjectUuid    string                 `protobuf:"bytes,2,opt,name=project_uuid,json=projectUuid,proto3" json:"project_uuid,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cidr           string                 `protobuf:"bytes,4,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Gateway        string                 `protobuf:"bytes,5,opt,name=gateway,proto3" json:"gateway,omitempty"`
	DnsServers     []string               `protobuf:"bytes,6,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	Type           string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	MeshListenPort int32                  `protobuf:"varint,8,opt,name=mesh_listen_port,json=meshListenPort,proto3" json:"mesh_listen_port,omitempty"`
	MeshEndpoint   string                 `protobuf:"bytes,9,opt,name=mesh_endpoint,json=meshEndpoint,proto3" json:"mesh_endpoint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkSpec) Reset() {
	*x = NetworkSpec{}
	mi := &file_driverpb_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSpec) ProtoMessage() {}

func (x *NetworkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSpec.ProtoReflect.Descriptor instead.
func (*NetworkSpec) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkSpec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NetworkSpec) GetProjectUuid() string {
	if x != nil {
		return x.ProjectUuid
	}
	return ""
}

func (x *NetworkSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkSpec) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkSpec) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *NetworkSpec) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *NetworkSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NetworkSpec) GetMeshListenPort() int32 {
	if x != nil {
		return x.MeshListenPort
	}
	return 0
}

func (x *NetworkSpec) GetMeshEndpoint() string {
	if x != nil {
		return x.MeshEndpoint
	}
	return ""
}

type PortSpec struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Uuid                    string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ProjectUuid             string                 `protobuf:"bytes,2,opt,name=project_uuid,json=projectUuid,proto3" json:"project_uuid,omitempty"`
	VmUuid                  string                 `protobuf:"bytes,3,opt,name=vm_uuid,json=vmUuid,proto3" json:"vm_uuid,omitempty"`
	NetworkUuid             string                 `protobuf:"bytes,4,opt,name=network_uuid,json=networkUuid,proto3" json:"network_uuid,omitempty"`
	Mac                     string                 `protobuf:"bytes,5,opt,name=mac,proto3" json:"mac,omitempty"`
	Ip                      string                 `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	WireguardPubKey         string                 `protobuf:"bytes,7,opt,name=wireguard_pub_key,json=wireguardPubKey,proto3" json:"wireguard_pub_key,omitempty"`
	MeshEndpoint            string                 `protobuf:"bytes,8,opt,name=mesh_endpoint,json=meshEndpoint,proto3" json:"mesh_endpoint,omitempty"`
	EffectiveSecurityGroups []string               `protobuf:"bytes,9,rep,name=effective_security_groups,json=effectiveSecurityGroups,proto3" json:"effective_security_groups,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PortSpec) Reset() {
	*x = PortSpec{}
	mi := &file_driverpb_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpec) ProtoMessage() {}

func (x *PortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpec.ProtoReflect.Descriptor instead.
func (*PortSpec) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{6}
}

func (x *PortSpec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PortSpec) GetProjectUuid() string {
	if x != nil {
		return x.ProjectUuid
	}
	return ""
}

func (x *PortSpec) GetVmUuid() string {
	if x != nil {
		return x.VmUuid
	}
	return ""
}

func (x *PortSpec) GetNetworkUuid() string {
	if x != nil {
		return x.NetworkUuid
	}
	return ""
}

func (x *PortSpec) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *PortSpec) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PortSpec) GetWireguardPubKey() string {
	if x != nil {
		return x.WireguardPubKey
	}
	return ""
}

func (x *PortSpec) GetMeshEndpoint() string {
	if x != nil {
		return x.MeshEndpoint
	}
	return ""
}

func (x *PortSpec) GetEffectiveSecurityGroups() []string {
	if x != nil {
		return x.EffectiveSecurityGroups
	}
	return nil
}

type VolumeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ProjectUuid   string                 `protobuf:"bytes,2,opt,name=project_uuid,json=projectUuid,proto3" json:"project_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SizeGib       int32                  `protobuf:"varint,4,opt,name=size_gib,json=sizeGib,proto3" json:"size_gib,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeSpec) Reset() {
	*x = VolumeSpec{}
	mi := &file_driverpb_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeSpec) ProtoMessage() {}

func (x *VolumeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeSpec.ProtoReflect.Descriptor instead.
func (*VolumeSpec) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{7}
}

func (x *VolumeSpec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VolumeSpec) GetProjectUuid() string {
	if x != nil {
		return x.ProjectUuid
	}
	return ""
}

func (x *VolumeSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeSpec) GetSizeGib() int32 {
	if x != nil {
		return x.SizeGib
	}
	return 0
}

func (x *VolumeSpec) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type AttachedVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackingPath   string                 `protobuf:"bytes,1,opt,name=backing_path,json=backingPath,proto3" json:"backing_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,2,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachedVolume) Reset() {
	*x = AttachedVolume{}
	mi := &file_driverpb_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachedVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachedVolume) ProtoMessage() {}

func (x *AttachedVolume) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachedVolume.ProtoReflect.Descriptor instead.
func (*AttachedVolume) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{8}
}

func (x *AttachedVolume) GetBackingPath() string {
	if x != nil {
		return x.BackingPath
	}
	return ""
}

func (x *AttachedVolume) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *VMSpec                `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVMRequest) GetSpec() *VMSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type VMUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmUuid        string                 `protobuf:"bytes,1,opt,name=vm_uuid,json=vmUuid,proto3" json:"vm_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMUUIDRequest) Reset() {
	*x = VMUUIDRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMUUIDRequest) ProtoMessage() {}

func (x *VMUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMUUIDRequest.ProtoReflect.Descriptor instead.
func (*VMUUIDRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{10}
}

func (x *VMUUIDRequest) GetVmUuid() string {
	if x != nil {
		return x.VmUuid
	}
	return ""
}

type AttachDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmUuid        string                 `protobuf:"bytes,1,opt,name=vm_uuid,json=vmUuid,proto3" json:"vm_uuid,omitempty"`
	Disk          *DiskSpec              `protobuf:"bytes,2,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDiskRequest) Reset() {
	*x = AttachDiskRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDiskRequest) ProtoMessage() {}

func (x *AttachDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDiskRequest.ProtoReflect.Descriptor instead.
func (*AttachDiskRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{11}
}

func (x *AttachDiskRequest) GetVmUuid() string {
	if x != nil {
		return x.VmUuid
	}
	return ""
}

func (x *AttachDiskRequest) GetDisk() *DiskSpec {
	if x != nil {
		return x.Disk
	}
	return nil
}

type DetachDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmUuid        string                 `protobuf:"bytes,1,opt,name=vm_uuid,json=vmUuid,proto3" json:"vm_uuid,omitempty"`
	VolumeUuid    string                 `protobuf:"bytes,2,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachDiskRequest) Reset() {
	*x = DetachDiskRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDiskRequest) ProtoMessage() {}

func (x *DetachDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDiskRequest.ProtoReflect.Descriptor instead.
func (*DetachDiskRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{12}
}

func (x *DetachDiskRequest) GetVmUuid() string {
	if x != nil {
		return x.VmUuid
	}
	return ""
}

func (x *DetachDiskRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

type AttachNICRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmUuid        string                 `protobuf:"bytes,1,opt,name=vm_uuid,json=vmUuid,proto3" json:"vm_uuid,omitempty"`
	Nic           *NICHandle             `protobuf:"bytes,2,opt,name=nic,proto3" json:"nic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachNICRequest) Reset() {
	*x = AttachNICRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachNICRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachNICRequest) ProtoMessage() {}

func (x *AttachNICRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachNICRequest.ProtoReflect.Descriptor instead.
func (*AttachNICRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{13}
}

func (x *AttachNICRequest) GetVmUuid() string {
	if x != nil {
		return x.VmUuid
	}
	return ""
}

func (x *AttachNICRequest) GetNic() *NICHandle {
	if x != nil {
		return x.Nic
	}
	return nil
}

type DetachNICRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmUuid        string                 `protobuf:"bytes,1,opt,name=vm_uuid,json=vmUuid,proto3" json:"vm_uuid,omitempty"`
	NicDevice     string                 `protobuf:"bytes,2,opt,name=nic_device,json=nicDevice,proto3" json:"nic_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachNICRequest) Reset() {
	*x = DetachNICRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachNICRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachNICRequest) ProtoMessage() {}

func (x *DetachNICRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachNICRequest.ProtoReflect.Descriptor instead.
func (*DetachNICRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{14}
}

func (x *DetachNICRequest) GetVmUuid() string {
	if x != nil {
		return x.VmUuid
	}
	return ""
}

func (x *DetachNICRequest) GetNicDevice() string {
	if x != nil {
		return x.NicDevice
	}
	return ""
}

type EnsureNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *NetworkSpec           `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureNetworkRequest) Reset() {
	*x = EnsureNetworkRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureNetworkRequest) ProtoMessage() {}

func (x *EnsureNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureNetworkRequest.ProtoReflect.Descriptor instead.
func (*EnsureNetworkRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{15}
}

func (x *EnsureNetworkRequest) GetSpec() *NetworkSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DestroyNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkUuid   string                 `protobuf:"bytes,1,opt,name=network_uuid,json=networkUuid,proto3" json:"network_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyNetworkRequest) Reset() {
	*x = DestroyNetworkRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyNetworkRequest) ProtoMessage() {}

func (x *DestroyNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyNetworkRequest.ProtoReflect.Descriptor instead.
func (*DestroyNetworkRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{16}
}

func (x *DestroyNetworkRequest) GetNetworkUuid() string {
	if x != nil {
		return x.NetworkUuid
	}
	return ""
}

type AttachPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *PortSpec              `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPortRequest) Reset() {
	*x = AttachPortRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPortRequest) ProtoMessage() {}

func (x *AttachPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPortRequest.ProtoReflect.Descriptor instead.
func (*AttachPortRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{17}
}

func (x *AttachPortRequest) GetSpec() *PortSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type AttachPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *NICHandle             `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPortResponse) Reset() {
	*x = AttachPortResponse{}
	mi := &file_driverpb_driver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPortResponse) ProtoMessage() {}

func (x *AttachPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPortResponse.ProtoReflect.Descriptor instead.
func (*AttachPortResponse) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{18}
}

func (x *AttachPortResponse) GetHandle() *NICHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

type DetachPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortUuid      string                 `protobuf:"bytes,1,opt,name=port_uuid,json=portUuid,proto3" json:"port_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachPortRequest) Reset() {
	*x = DetachPortRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachPortRequest) ProtoMessage() {}

func (x *DetachPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachPortRequest.ProtoReflect.Descriptor instead.
func (*DetachPortRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{19}
}

func (x *DetachPortRequest) GetPortUuid() string {
	if x != nil {
		return x.PortUuid
	}
	return ""
}

type RotateMeshPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *PortSpec              `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateMeshPeerRequest) Reset() {
	*x = RotateMeshPeerRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateMeshPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateMeshPeerRequest) ProtoMessage() {}

func (x *RotateMeshPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateMeshPeerRequest.ProtoReflect.Descriptor instead.
func (*RotateMeshPeerRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{20}
}

func (x *RotateMeshPeerRequest) GetSpec() *PortSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_driverpb_driver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{21}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LocalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Local         bool                   `protobuf:"varint,1,opt,name=local,proto3" json:"local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalResponse) Reset() {
	*x = LocalResponse{}
	mi := &file_driverpb_driver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalResponse) ProtoMessage() {}

func (x *LocalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalResponse.ProtoReflect.Descriptor instead.
func (*LocalResponse) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{22}
}

func (x *LocalResponse) GetLocal() bool {
	if x != nil {
		return x.Local
	}
	return false
}

type EnsureVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *VolumeSpec            `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureVolumeRequest) Reset() {
	*x = EnsureVolumeRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureVolumeRequest) ProtoMessage() {}

func (x *EnsureVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureVolumeRequest.ProtoReflect.Descriptor instead.
func (*EnsureVolumeRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{23}
}

func (x *EnsureVolumeRequest) GetSpec() *VolumeSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DestroyVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeUuid    string                 `protobuf:"bytes,1,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVolumeRequest) Reset() {
	*x = DestroyVolumeRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVolumeRequest) ProtoMessage() {}

func (x *DestroyVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVolumeRequest.ProtoReflect.Descriptor instead.
func (*DestroyVolumeRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{24}
}

func (x *DestroyVolumeRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

type AttachVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeUuid    string                 `protobuf:"bytes,1,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	HostUuid      string                 `protobuf:"bytes,2,opt,name=host_uuid,json=hostUuid,proto3" json:"host_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachVolumeRequest) Reset() {
	*x = AttachVolumeRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachVolumeRequest) ProtoMessage() {}

func (x *AttachVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachVolumeRequest.ProtoReflect.Descriptor instead.
func (*AttachVolumeRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{25}
}

func (x *AttachVolumeRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *AttachVolumeRequest) GetHostUuid() string {
	if x != nil {
		return x.HostUuid
	}
	return ""
}

type AttachVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *AttachedVolume        `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachVolumeResponse) Reset() {
	*x = AttachVolumeResponse{}
	mi := &file_driverpb_driver_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachVolumeResponse) ProtoMessage() {}

func (x *AttachVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachVolumeResponse.ProtoReflect.Descriptor instead.
func (*AttachVolumeResponse) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{26}
}

func (x *AttachVolumeResponse) GetVolume() *AttachedVolume {
	if x != nil {
		return x.Volume
	}
	return nil
}

type DetachVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeUuid    string                 `protobuf:"bytes,1,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	HostUuid      string                 `protobuf:"bytes,2,opt,name=host_uuid,json=hostUuid,proto3" json:"host_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachVolumeRequest) Reset() {
	*x = DetachVolumeRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachVolumeRequest) ProtoMessage() {}

func (x *DetachVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachVolumeRequest.ProtoReflect.Descriptor instead.
func (*DetachVolumeRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{27}
}

func (x *DetachVolumeRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *DetachVolumeRequest) GetHostUuid() string {
	if x != nil {
		return x.HostUuid
	}
	return ""
}

type RefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefRequest) Reset() {
	*x = RefRequest{}
	mi := &file_driverpb_driver_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefRequest) ProtoMessage() {}

func (x *RefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefRequest.ProtoReflect.Descriptor instead.
func (*RefRequest) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{28}
}

func (x *RefRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type LocalPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalPathResponse) Reset() {
	*x = LocalPathResponse{}
	mi := &file_driverpb_driver_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalPathResponse) ProtoMessage() {}

func (x *LocalPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalPathResponse.ProtoReflect.Descriptor instead.
func (*LocalPathResponse) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{29}
}

func (x *LocalPathResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type InCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InCache       bool                   `protobuf:"varint,1,opt,name=in_cache,json=inCache,proto3" json:"in_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InCacheResponse) Reset() {
	*x = InCacheResponse{}
	mi := &file_driverpb_driver_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InCacheResponse) ProtoMessage() {}

func (x *InCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverpb_driver_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InCacheResponse.ProtoReflect.Descriptor instead.
func (*InCacheResponse) Descriptor() ([]byte, []int) {
	return file_driverpb_driver_proto_rawDescGZIP(), []int{30}
}

func (x *InCacheResponse) GetInCache() bool {
	if x != nil {
		return x.InCache
	}
	return false
}

var File_driverpb_driver_proto protoreflect.FileDescriptor

const file_driverpb_driver_proto_rawDesc = "" +
	"\n" +
	"\x15driverpb/driver.proto\x12\x0eweft.driver.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x8e\x01\n" +
	"\bHostInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02az\x18\x03 \x01(\tR\x02az\x12\x1e\n" +
	"\n" +
	"hypervisor\x18\x04 \x01(\tR\n" +
	"hypervisor\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\"I\n" +
	"\x10HostInfoResponse\x125\n" +
	"\thost_info\x18\x01 \x01(\v2\x18.weft.driver.v1.HostInfoR\bhostInfo\"\xe1\x01\n" +
	"\x06VMSpec\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\fproject_uuid\x18\x02 \x01(\tR\vprojectUuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tcpu_count\x18\x04 \x01(\x05R\bcpuCount\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x05 \x01(\x05R\tmemoryMib\x12\x1b\n" +
	"\tboot_kind\x18\x06 \x01(\tR\bbootKind\x12\x19\n" +
	"\bboot_ref\x18\a \x01(\tR\abootRef\x12\x18\n" +
	"\acmdline\x18\b \x01(\tR\acmdline\"\xac\x01\n" +
	"\bDiskSpec\x12\x1f\n" +
	"\vvolume_uuid\x18\x01 \x01(\tR\n" +
	"volumeUuid\x12!\n" +
	"\fbacking_path\x18\x02 \x01(\tR\vbackingPath\x12\x10\n" +
	"\x03bus\x18\x03 \x01(\tR\x03bus\x12\x19\n" +
	"\bsize_gib\x18\x04 \x01(\x05R\asizeGib\x12\x1b\n" +
	"\tread_only\x18\x05 \x01(\bR\breadOnly\x12\x12\n" +
	"\x04boot\x18\x06 \x01(\bR\x04boot\"5\n" +
	"\tNICHandle\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\"\x8a\x02\n" +
	"\vNetworkSpec\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\fproject_uuid\x18\x02 \x01(\tR\vprojectUuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04cidr\x18\x04 \x01(\tR\x04cidr\x12\x18\n" +
	"\agateway\x18\x05 \x01(\tR\agateway\x12\x1f\n" +
	"\vdns_servers\x18\x06 \x03(\tR\n" +
	"dnsServers\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12(\n" +
	"\x10mesh_listen_port\x18\b \x01(\x05R\x0emeshListenPort\x12#\n" +
	"\rmesh_endpoint\x18\t \x01(\tR\fmeshEndpoint\"\xac\x02\n" +
	"\bPortSpec\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\fproject_uuid\x18\x02 \x01(\tR\vprojectUuid\x12\x17\n" +
	"\avm_uuid\x18\x03 \x01(\tR\x06vmUuid\x12!\n" +
	"\fnetwork_uuid\x18\x04 \x01(\tR\vnetworkUuid\x12\x10\n" +
	"\x03mac\x18\x05 \x01(\tR\x03mac\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip\x12*\n" +
	"\x11wireguard_pub_key\x18\a \x01(\tR\x0fwireguardPubKey\x12#\n" +
	"\rmesh_endpoint\x18\b \x01(\tR\fmeshEndpoint\x12:\n" +
	"\x19effective_security_groups\x18\t \x03(\tR\x17effectiveSecurityGroups\"\x8a\x01\n" +
	"\n" +
	"VolumeSpec\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\fproject_uuid\x18\x02 \x01(\tR\vprojectUuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bsize_gib\x18\x04 \x01(\x05R\asizeGib\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"P\n" +
	"\x0eAttachedVolume\x12!\n" +
	"\fbacking_path\x18\x01 \x01(\tR\vbackingPath\x12\x1b\n" +
	"\tread_only\x18\x02 \x01(\bR\breadOnly\"=\n" +
	"\x0fCreateVMRequest\x12*\n" +
	"\x04spec\x18\x01 \x01(\v2\x16.weft.driver.v1.VMSpecR\x04spec\"(\n" +
	"\rVMUUIDRequest\x12\x17\n" +
	"\avm_uuid\x18\x01 \x01(\tR\x06vmUuid\"Z\n" +
	"\x11AttachDiskRequest\x12\x17\n" +
	"\avm_uuid\x18\x01 \x01(\tR\x06vmUuid\x12,\n" +
	"\x04disk\x18\x02 \x01(\v2\x18.weft.driver.v1.DiskSpecR\x04disk\"M\n" +
	"\x11DetachDiskRequest\x12\x17\n" +
	"\avm_uuid\x18\x01 \x01(\tR\x06vmUuid\x12\x1f\n" +
	"\vvolume_uuid\x18\x02 \x01(\tR\n" +
	"volumeUuid\"X\n" +
	"\x10AttachNICRequest\x12\x17\n" +
	"\avm_uuid\x18\x01 \x01(\tR\x06vmUuid\x12+\n" +
	"\x03nic\x18\x02 \x01(\v2\x19.weft.driver.v1.NICHandleR\x03nic\"J\n" +
	"\x10DetachNICRequest\x12\x17\n" +
	"\avm_uuid\x18\x01 \x01(\tR\x06vmUuid\x12\x1d\n" +
	"\n" +
	"nic_device\x18\x02 \x01(\tR\tnicDevice\"G\n" +
	"\x14EnsureNetworkRequest\x12/\n" +
	"\x04spec\x18\x01 \x01(\v2\x1b.weft.driver.v1.NetworkSpecR\x04spec\":\n" +
	"\x15DestroyNetworkRequest\x12!\n" +
	"\fnetwork_uuid\x18\x01 \x01(\tR\vnetworkUuid\"A\n" +
	"\x11AttachPortRequest\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.weft.driver.v1.PortSpecR\x04spec\"G\n" +
	"\x12AttachPortResponse\x121\n" +
	"\x06handle\x18\x01 \x01(\v2\x19.weft.driver.v1.NICHandleR\x06handle\"0\n" +
	"\x11DetachPortRequest\x12\x1b\n" +
	"\tport_uuid\x18\x01 \x01(\tR\bportUuid\"E\n" +
	"\x15RotateMeshPeerRequest\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.weft.driver.v1.PortSpecR\x04spec\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"%\n" +
	"\rLocalResponse\x12\x14\n" +
	"\x05local\x18\x01 \x01(\bR\x05local\"E\n" +
	"\x13EnsureVolumeRequest\x12.\n" +
	"\x04spec\x18\x01 \x01(\v2\x1a.weft.driver.v1.VolumeSpecR\x04spec\"7\n" +
	"\x14DestroyVolumeRequest\x12\x1f\n" +
	"\vvolume_uuid\x18\x01 \x01(\tR\n" +
	"volumeUuid\"S\n" +
	"\x13AttachVolumeRequest\x12\x1f\n" +
	"\vvolume_uuid\x18\x01 \x01(\tR\n" +
	"volumeUuid\x12\x1b\n" +
	"\thost_uuid\x18\x02 \x01(\tR\bhostUuid\"N\n" +
	"\x14AttachVolumeResponse\x126\n" +
	"\x06volume\x18\x01 \x01(\v2\x1e.weft.driver.v1.AttachedVolumeR\x06volume\"S\n" +
	"\x13DetachVolumeRequest\x12\x1f\n" +
	"\vvolume_uuid\x18\x01 \x01(\tR\n" +
	"volumeUuid\x12\x1b\n" +
	"\thost_uuid\x18\x02 \x01(\tR\bhostUuid\"\x1e\n" +
	"\n" +
	"RefRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"'\n" +
	"\x11LocalPathResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x0fInCacheResponse\x12\x19\n" +
	"\bin_cache\x18\x01 \x01(\bR\ainCache2\xfd\x04\n" +
	"\n" +
	"Hypervisor\x12D\n" +
	"\bHostInfo\x12\x16.google.protobuf.Empty\x1a .weft.driver.v1.HostInfoResponse\x12C\n" +
	"\bCreateVM\x12\x1f.weft.driver.v1.CreateVMRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\aStartVM\x12\x1d.weft.driver.v1.VMUUIDRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x06StopVM\x12\x1d.weft.driver.v1.VMUUIDRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\bDeleteVM\x12\x1d.weft.driver.v1.VMUUIDRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\n" +
	"AttachDisk\x12!.weft.driver.v1.AttachDiskRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\n" +
	"DetachDisk\x12!.weft.driver.v1.DetachDiskRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\tAttachNIC\x12 .weft.driver.v1.AttachNICRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\tDetachNIC\x12 .weft.driver.v1.DetachNICRequest\x1a\x16.google.protobuf.Empty2\xde\x03\n" +
	"\aNetwork\x12D\n" +
	"\bHostInfo\x12\x16.google.protobuf.Empty\x1a .weft.driver.v1.HostInfoResponse\x12M\n" +
	"\rEnsureNetwork\x12$.weft.driver.v1.EnsureNetworkRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x0eDestroyNetwork\x12%.weft.driver.v1.DestroyNetworkRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\n" +
	"AttachPort\x12!.weft.driver.v1.AttachPortRequest\x1a\".weft.driver.v1.AttachPortResponse\x12G\n" +
	"\n" +
	"DetachPort\x12!.weft.driver.v1.DetachPortRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x0eRotateMeshPeer\x12%.weft.driver.v1.RotateMeshPeerRequest\x1a\x16.google.protobuf.Empty2\x90\x04\n" +
	"\x06Volume\x12<\n" +
	"\x04Name\x12\x16.google.protobuf.Empty\x1a\x1c.weft.driver.v1.NameResponse\x12>\n" +
	"\x05Local\x12\x16.google.protobuf.Empty\x1a\x1d.weft.driver.v1.LocalResponse\x12D\n" +
	"\bHostInfo\x12\x16.google.protobuf.Empty\x1a .weft.driver.v1.HostInfoResponse\x12K\n" +
	"\fEnsureVolume\x12#.weft.driver.v1.EnsureVolumeRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\rDestroyVolume\x12$.weft.driver.v1.DestroyVolumeRequest\x1a\x16.google.protobuf.Empty\x12Y\n" +
	"\fAttachVolume\x12#.weft.driver.v1.AttachVolumeRequest\x1a$.weft.driver.v1.AttachVolumeResponse\x12K\n" +
	"\fDetachVolume\x12#.weft.driver.v1.DetachVolumeRequest\x1a\x16.google.protobuf.Empty2\xdb\x02\n" +
	"\x05Image\x12D\n" +
	"\bHostInfo\x12\x16.google.protobuf.Empty\x1a .weft.driver.v1.HostInfoResponse\x12:\n" +
	"\x04Pull\x12\x1a.weft.driver.v1.RefRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\tLocalPath\x12\x1a.weft.driver.v1.RefRequest\x1a!.weft.driver.v1.LocalPathResponse\x12<\n" +
	"\x06Delete\x12\x1a.weft.driver.v1.RefRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\aInCache\x12\x1a.weft.driver.v1.RefRequest\x1a\x1f.weft.driver.v1.InCacheResponseB1Z/github.com/openweft/weft-driver-plugin/driverpbb\x06proto3"

var (
	file_driverpb_driver_proto_rawDescOnce sync.Once
	file_driverpb_driver_proto_rawDescData []byte
)

func file_driverpb_driver_proto_rawDescGZIP() []byte {
	file_driverpb_driver_proto_rawDescOnce.Do(func() {
		file_driverpb_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driverpb_driver_proto_rawDesc), len(file_driverpb_driver_proto_rawDesc)))
	})
	return file_driverpb_driver_proto_rawDescData
}

var file_driverpb_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_driverpb_driver_proto_goTypes = []any{
	(*HostInfo)(nil),              // 0: weft.driver.v1.HostInfo
	(*HostInfoResponse)(nil),      // 1: weft.driver.v1.HostInfoResponse
	(*VMSpec)(nil),                // 2: weft.driver.v1.VMSpec
	(*DiskSpec)(nil),              // 3: weft.driver.v1.DiskSpec
	(*NICHandle)(nil),             // 4: weft.driver.v1.NICHandle
	(*NetworkSpec)(nil),           // 5: weft.driver.v1.NetworkSpec
	(*PortSpec)(nil),              // 6: weft.driver.v1.PortSpec
	(*VolumeSpec)(nil),            // 7: weft.driver.v1.VolumeSpec
	(*AttachedVolume)(nil),        // 8: weft.driver.v1.AttachedVolume
	(*CreateVMRequest)(nil),       // 9: weft.driver.v1.CreateVMRequest
	(*VMUUIDRequest)(nil),         // 10: weft.driver.v1.VMUUIDRequest
	(*AttachDiskRequest)(nil),     // 11: weft.driver.v1.AttachDiskRequest
	(*DetachDiskRequest)(nil),     // 12: weft.driver.v1.DetachDiskRequest
	(*AttachNICRequest)(nil),      // 13: weft.driver.v1.AttachNICRequest
	(*DetachNICRequest)(nil),      // 14: weft.driver.v1.DetachNICRequest
	(*EnsureNetworkRequest)(nil),  // 15: weft.driver.v1.EnsureNetworkRequest
	(*DestroyNetworkRequest)(nil), // 16: weft.driver.v1.DestroyNetworkRequest
	(*AttachPortRequest)(nil),     // 17: weft.driver.v1.AttachPortRequest
	(*AttachPortResponse)(nil),    // 18: weft.driver.v1.AttachPortResponse
	(*DetachPortRequest)(nil),     // 19: weft.driver.v1.DetachPortRequest
	(*RotateMeshPeerRequest)(nil), // 20: weft.driver.v1.RotateMeshPeerRequest
	(*NameResponse)(nil),          // 21: weft.driver.v1.NameResponse
	(*LocalResponse)(nil),         // 22: weft.driver.v1.LocalResponse
	(*EnsureVolumeRequest)(nil),   // 23: weft.driver.v1.EnsureVolumeRequest
	(*DestroyVolumeRequest)(nil),  // 24: weft.driver.v1.DestroyVolumeRequest
	(*AttachVolumeRequest)(nil),   // 25: weft.driver.v1.AttachVolumeRequest
	(*AttachVolumeResponse)(nil),  // 26: weft.driver.v1.AttachVolumeResponse
	(*DetachVolumeRequest)(nil),   // 27: weft.driver.v1.DetachVolumeRequest
	(*RefRequest)(nil),            // 28: weft.driver.v1.RefRequest
	(*LocalPathResponse)(nil),     // 29: weft.driver.v1.LocalPathResponse
	(*InCacheResponse)(nil),       // 30: weft.driver.v1.InCacheResponse
	(*emptypb.Empty)(nil),         // 31: google.protobuf.Empty
}
var file_driverpb_driver_proto_depIdxs = []int32{
	0,  // 0: weft.driver.v1.HostInfoResponse.host_info:type_name -> weft.driver.v1.HostInfo
	2,  // 1: weft.driver.v1.CreateVMRequest.spec:type_name -> weft.driver.v1.VMSpec
	3,  // 2: weft.driver.v1.AttachDiskRequest.disk:type_name -> weft.driver.v1.DiskSpec
	4,  // 3: weft.driver.v1.AttachNICRequest.nic:type_name -> weft.driver.v1.NICHandle
	5,  // 4: weft.driver.v1.EnsureNetworkRequest.spec:type_name -> weft.driver.v1.NetworkSpec
	6,  // 5: weft.driver.v1.AttachPortRequest.spec:type_name -> weft.driver.v1.PortSpec
	4,  // 6: weft.driver.v1.AttachPortResponse.handle:type_name -> weft.driver.v1.NICHandle
	6,  // 7: weft.driver.v1.RotateMeshPeerRequest.spec:type_name -> weft.driver.v1.PortSpec
	7,  // 8: weft.driver.v1.EnsureVolumeRequest.spec:type_name -> weft.driver.v1.VolumeSpec
	8,  // 9: weft.driver.v1.AttachVolumeResponse.volume:type_name -> weft.driver.v1.AttachedVolume
	31, // 10: weft.driver.v1.Hypervisor.HostInfo:input_type -> google.protobuf.Empty
	9,  // 11: weft.driver.v1.Hypervisor.CreateVM:input_type -> weft.driver.v1.CreateVMRequest
	10, // 12: weft.driver.v1.Hypervisor.StartVM:input_type -> weft.driver.v1.VMUUIDRequest
	10, // 13: weft.driver.v1.Hypervisor.StopVM:input_type -> weft.driver.v1.VMUUIDRequest
	10, // 14: weft.driver.v1.Hypervisor.DeleteVM:input_type -> weft.driver.v1.VMUUIDRequest
	11, // 15: weft.driver.v1.Hypervisor.AttachDisk:input_type -> weft.driver.v1.AttachDiskRequest
	12, // 16: weft.driver.v1.Hypervisor.DetachDisk:input_type -> weft.driver.v1.DetachDiskRequest
	13, // 17: weft.driver.v1.Hypervisor.AttachNIC:input_type -> weft.driver.v1.AttachNICRequest
	14, // 18: weft.driver.v1.Hypervisor.DetachNIC:input_type -> weft.driver.v1.DetachNICRequest
	31, // 19: weft.driver.v1.Network.HostInfo:input_type -> google.protobuf.Empty
	15, // 20: weft.driver.v1.Network.EnsureNetwork:input_type -> weft.driver.v1.EnsureNetworkRequest
	16, // 21: weft.driver.v1.Network.DestroyNetwork:input_type -> weft.driver.v1.DestroyNetworkRequest
	17, // 22: weft.driver.v1.Network.AttachPort:input_type -> weft.driver.v1.AttachPortRequest
	19, // 23: weft.driver.v1.Network.DetachPort:input_type -> weft.driver.v1.DetachPortRequest
	20, // 24: weft.driver.v1.Network.RotateMeshPeer:input_type -> weft.driver.v1.RotateMeshPeerRequest
	31, // 25: weft.driver.v1.Volume.Name:input_type -> google.protobuf.Empty
	31, // 26: weft.driver.v1.Volume.Local:input_type -> google.protobuf.Empty
	31, // 27: weft.driver.v1.Volume.HostInfo:input_type -> google.protobuf.Empty
	23, // 28: weft.driver.v1.Volume.EnsureVolume:input_type -> weft.driver.v1.EnsureVolumeRequest
	24, // 29: weft.driver.v1.Volume.DestroyVolume:input_type -> weft.driver.v1.DestroyVolumeRequest
	25, // 30: weft.driver.v1.Volume.AttachVolume:input_type -> weft.driver.v1.AttachVolumeRequest
	27, // 31: weft.driver.v1.Volume.DetachVolume:input_type -> weft.driver.v1.DetachVolumeRequest
	31, // 32: weft.driver.v1.Image.HostInfo:input_type -> google.protobuf.Empty
	28, // 33: weft.driver.v1.Image.Pull:input_type -> weft.driver.v1.RefRequest
	28, // 34: weft.driver.v1.Image.LocalPath:input_type -> weft.driver.v1.RefRequest
	28, // 35: weft.driver.v1.Image.Delete:input_type -> weft.driver.v1.RefRequest
	28, // 36: weft.driver.v1.Image.InCache:input_type -> weft.driver.v1.RefRequest
	1,  // 37: weft.driver.v1.Hypervisor.HostInfo:output_type -> weft.driver.v1.HostInfoResponse
	31, // 38: weft.driver.v1.Hypervisor.CreateVM:output_type -> google.protobuf.Empty
	31, // 39: weft.driver.v1.Hypervisor.StartVM:output_type -> google.protobuf.Empty
	31, // 40: weft.driver.v1.Hypervisor.StopVM:output_type -> google.protobuf.Empty
	31, // 41: weft.driver.v1.Hypervisor.DeleteVM:output_type -> google.protobuf.Empty
	31, // 42: weft.driver.v1.Hypervisor.AttachDisk:output_type -> google.protobuf.Empty
	31, // 43: weft.driver.v1.Hypervisor.DetachDisk:output_type -> google.protobuf.Empty
	31, // 44: weft.driver.v1.Hypervisor.AttachNIC:output_type -> google.protobuf.Empty
	31, // 45: weft.driver.v1.Hypervisor.DetachNIC:output_type -> google.protobuf.Empty
	1,  // 46: weft.driver.v1.Network.HostInfo:output_type -> weft.driver.v1.HostInfoResponse
	31, // 47: weft.driver.v1.Network.EnsureNetwork:output_type -> google.protobuf.Empty
	31, // 48: weft.driver.v1.Network.DestroyNetwork:output_type -> google.protobuf.Empty
	18, // 49: weft.driver.v1.Network.AttachPort:output_type -> weft.driver.v1.AttachPortResponse
	31, // 50: weft.driver.v1.Network.DetachPort:output_type -> google.protobuf.Empty
	31, // 51: weft.driver.v1.Network.RotateMeshPeer:output_type -> google.protobuf.Empty
	21, // 52: weft.driver.v1.Volume.Name:output_type -> weft.driver.v1.NameResponse
	22, // 53: weft.driver.v1.Volume.Local:output_type -> weft.driver.v1.LocalResponse
	1,  // 54: weft.driver.v1.Volume.HostInfo:output_type -> weft.driver.v1.HostInfoResponse
	31, // 55: weft.driver.v1.Volume.EnsureVolume:output_type -> google.protobuf.Empty
	31, // 56: weft.driver.v1.Volume.DestroyVolume:output_type -> google.protobuf.Empty
	26, // 57: weft.driver.v1.Volume.AttachVolume:output_type -> weft.driver.v1.AttachVolumeResponse
	31, // 58: weft.driver.v1.Volume.DetachVolume:output_type -> google.protobuf.Empty
	1,  // 59: weft.driver.v1.Image.HostInfo:output_type -> weft.driver.v1.HostInfoResponse
	31, // 60: weft.driver.v1.Image.Pull:output_type -> google.protobuf.Empty
	29, // 61: weft.driver.v1.Image.LocalPath:output_type -> weft.driver.v1.LocalPathResponse
	31, // 62: weft.driver.v1.Image.Delete:output_type -> google.protobuf.Empty
	30, // 63: weft.driver.v1.Image.InCache:output_type -> weft.driver.v1.InCacheResponse
	37, // [37:64] is the sub-list for method output_type
	10, // [10:37] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_driverpb_driver_proto_init() }
func file_driverpb_driver_proto_init() {
	if File_driverpb_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driverpb_driver_proto_rawDesc), len(file_driverpb_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_driverpb_driver_proto_goTypes,
		DependencyIndexes: file_driverpb_driver_proto_depIdxs,
		MessageInfos:      file_driverpb_driver_proto_msgTypes,
	}.Build()
	File_driverpb_driver_proto = out.File
	file_driverpb_driver_proto_goTypes = nil
	file_driverpb_driver_proto_depIdxs = nil
}
