// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: driverpb/driver.proto

// Package weft.driver.v1 is the wire contract for the weft driver go-plugin
// transport. Each of the four driver interfaces in github.com/openweft/
// weft-drivers (HypervisorDriver, NetworkDriver, VolumeDriver, ImageDriver)
// maps to one gRPC service here, one RPC per interface method. All four are
// served by a single plugin process (one per host) and dispensed to the host
// as a DriverSet — see ../plugin.go.
//
// The messages mirror weft-drivers/types.go exactly. Those structs were
// designed flat + primitive-valued precisely so this mapping is mechanical:
// no nested maps, no pointers, no time.Time on the wire.

package driverpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hypervisor_HostInfo_FullMethodName   = "/weft.driver.v1.Hypervisor/HostInfo"
	Hypervisor_CreateVM_FullMethodName   = "/weft.driver.v1.Hypervisor/CreateVM"
	Hypervisor_StartVM_FullMethodName    = "/weft.driver.v1.Hypervisor/StartVM"
	Hypervisor_StopVM_FullMethodName     = "/weft.driver.v1.Hypervisor/StopVM"
	Hypervisor_DeleteVM_FullMethodName   = "/weft.driver.v1.Hypervisor/DeleteVM"
	Hypervisor_AttachDisk_FullMethodName = "/weft.driver.v1.Hypervisor/AttachDisk"
	Hypervisor_DetachDisk_FullMethodName = "/weft.driver.v1.Hypervisor/DetachDisk"
	Hypervisor_AttachNIC_FullMethodName  = "/weft.driver.v1.Hypervisor/AttachNIC"
	Hypervisor_DetachNIC_FullMethodName  = "/weft.driver.v1.Hypervisor/DetachNIC"
)

// HypervisorClient is the client API for Hypervisor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HypervisorClient interface {
	HostInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostInfoResponse, error)
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartVM(ctx context.Context, in *VMUUIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StopVM(ctx context.Context, in *VMUUIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteVM(ctx context.Context, in *VMUUIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AttachDisk(ctx context.Context, in *AttachDiskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DetachDisk(ctx context.Context, in *DetachDiskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AttachNIC(ctx context.Context, in *AttachNICRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DetachNIC(ctx context.Context, in *DetachNICRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type hypervisorClient struct {
	cc grpc.ClientConnInterface
}

func NewHypervisorClient(cc grpc.ClientConnInterface) HypervisorClient {
	return &hypervisorClient{cc}
}

func (c *hypervisorClient) HostInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostInfoResponse)
	err := c.cc.Invoke(ctx, Hypervisor_HostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hypervisor_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) StartVM(ctx context.Context, in *VMUUIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hypervisor_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) StopVM(ctx context.Context, in *VMUUIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hypervisor_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) DeleteVM(ctx context.Context, in *VMUUIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hypervisor_DeleteVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) AttachDisk(ctx context.Context, in *AttachDiskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hypervisor_AttachDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) DetachDisk(ctx context.Context, in *DetachDiskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hypervisor_DetachDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) AttachNIC(ctx context.Context, in *AttachNICRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hypervisor_AttachNIC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypervisorClient) DetachNIC(ctx context.Context, in *DetachNICRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hypervisor_DetachNIC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HypervisorServer is the server API for Hypervisor service.
// All implementations must embed UnimplementedHypervisorServer
// for forward compatibility.
type HypervisorServer interface {
	HostInfo(context.Context, *emptypb.Empty) (*HostInfoResponse, error)
	CreateVM(context.Context, *CreateVMRequest) (*emptypb.Empty, error)
	StartVM(context.Context, *VMUUIDRequest) (*emptypb.Empty, error)
	StopVM(context.Context, *VMUUIDRequest) (*emptypb.Empty, error)
	DeleteVM(context.Context, *VMUUIDRequest) (*emptypb.Empty, error)
	AttachDisk(context.Context, *AttachDiskRequest) (*emptypb.Empty, error)
	DetachDisk(context.Context, *DetachDiskRequest) (*emptypb.Empty, error)
	AttachNIC(context.Context, *AttachNICRequest) (*emptypb.Empty, error)
	DetachNIC(context.Context, *DetachNICRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedHypervisorServer()
}

// UnimplementedHypervisorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHypervisorServer struct{}

func (UnimplementedHypervisorServer) HostInfo(context.Context, *emptypb.Empty) (*HostInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HostInfo not implemented")
}
func (UnimplementedHypervisorServer) CreateVM(context.Context, *CreateVMRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedHypervisorServer) StartVM(context.Context, *VMUUIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedHypervisorServer) StopVM(context.Context, *VMUUIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedHypervisorServer) DeleteVM(context.Context, *VMUUIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedHypervisorServer) AttachDisk(context.Context, *AttachDiskRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachDisk not implemented")
}
func (UnimplementedHypervisorServer) DetachDisk(context.Context, *DetachDiskRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachDisk not implemented")
}
func (UnimplementedHypervisorServer) AttachNIC(context.Context, *AttachNICRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachNIC not implemented")
}
func (UnimplementedHypervisorServer) DetachNIC(context.Context, *DetachNICRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachNIC not implemented")
}
func (UnimplementedHypervisorServer) mustEmbedUnimplementedHypervisorServer() {}
func (UnimplementedHypervisorServer) testEmbeddedByValue()                    {}

// UnsafeHypervisorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HypervisorServer will
// result in compilation errors.
type UnsafeHypervisorServer interface {
	mustEmbedUnimplementedHypervisorServer()
}

func RegisterHypervisorServer(s grpc.ServiceRegistrar, srv HypervisorServer) {
	// If the following call panics, it indicates UnimplementedHypervisorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hypervisor_ServiceDesc, srv)
}

func _Hypervisor_HostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).HostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_HostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).HostInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).StartVM(ctx, req.(*VMUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).StopVM(ctx, req.(*VMUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).DeleteVM(ctx, req.(*VMUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_AttachDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).AttachDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_AttachDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).AttachDisk(ctx, req.(*AttachDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_DetachDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).DetachDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_DetachDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).DetachDisk(ctx, req.(*DetachDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_AttachNIC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachNICRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).AttachNIC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_AttachNIC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).AttachNIC(ctx, req.(*AttachNICRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypervisor_DetachNIC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachNICRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypervisorServer).DetachNIC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypervisor_DetachNIC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypervisorServer).DetachNIC(ctx, req.(*DetachNICRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hypervisor_ServiceDesc is the grpc.ServiceDesc for Hypervisor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hypervisor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weft.driver.v1.Hypervisor",
	HandlerType: (*HypervisorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostInfo",
			Handler:    _Hypervisor_HostInfo_Handler,
		},
		{
			MethodName: "CreateVM",
			Handler:    _Hypervisor_CreateVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _Hypervisor_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _Hypervisor_StopVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _Hypervisor_DeleteVM_Handler,
		},
		{
			MethodName: "AttachDisk",
			Handler:    _Hypervisor_AttachDisk_Handler,
		},
		{
			MethodName: "DetachDisk",
			Handler:    _Hypervisor_DetachDisk_Handler,
		},
		{
			MethodName: "AttachNIC",
			Handler:    _Hypervisor_AttachNIC_Handler,
		},
		{
			MethodName: "DetachNIC",
			Handler:    _Hypervisor_DetachNIC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driverpb/driver.proto",
}

const (
	Network_HostInfo_FullMethodName       = "/weft.driver.v1.Network/HostInfo"
	Network_EnsureNetwork_FullMethodName  = "/weft.driver.v1.Network/EnsureNetwork"
	Network_DestroyNetwork_FullMethodName = "/weft.driver.v1.Network/DestroyNetwork"
	Network_AttachPort_FullMethodName     = "/weft.driver.v1.Network/AttachPort"
	Network_DetachPort_FullMethodName     = "/weft.driver.v1.Network/DetachPort"
	Network_RotateMeshPeer_FullMethodName = "/weft.driver.v1.Network/RotateMeshPeer"
)

// NetworkClient is the client API for Network service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkClient interface {
	HostInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostInfoResponse, error)
	EnsureNetwork(ctx context.Context, in *EnsureNetworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DestroyNetwork(ctx context.Context, in *DestroyNetworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AttachPort(ctx context.Context, in *AttachPortRequest, opts ...grpc.CallOption) (*AttachPortResponse, error)
	DetachPort(ctx context.Context, in *DetachPortRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RotateMeshPeer(ctx context.Context, in *RotateMeshPeerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type networkClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkClient(cc grpc.ClientConnInterface) NetworkClient {
	return &networkClient{cc}
}

func (c *networkClient) HostInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostInfoResponse)
	err := c.cc.Invoke(ctx, Network_HostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) EnsureNetwork(ctx context.Context, in *EnsureNetworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Network_EnsureNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) DestroyNetwork(ctx context.Context, in *DestroyNetworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Network_DestroyNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) AttachPort(ctx context.Context, in *AttachPortRequest, opts ...grpc.CallOption) (*AttachPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachPortResponse)
	err := c.cc.Invoke(ctx, Network_AttachPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) DetachPort(ctx context.Context, in *DetachPortRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Network_DetachPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) RotateMeshPeer(ctx context.Context, in *RotateMeshPeerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Network_RotateMeshPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServer is the server API for Network service.
// All implementations must embed UnimplementedNetworkServer
// for forward compatibility.
type NetworkServer interface {
	HostInfo(context.Context, *emptypb.Empty) (*HostInfoResponse, error)
	EnsureNetwork(context.Context, *EnsureNetworkRequest) (*emptypb.Empty, error)
	DestroyNetwork(context.Context, *DestroyNetworkRequest) (*emptypb.Empty, error)
	AttachPort(context.Context, *AttachPortRequest) (*AttachPortResponse, error)
	DetachPort(context.Context, *DetachPortRequest) (*emptypb.Empty, error)
	RotateMeshPeer(context.Context, *RotateMeshPeerRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedNetworkServer()
}

// UnimplementedNetworkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkServer struct{}

func (UnimplementedNetworkServer) HostInfo(context.Context, *emptypb.Empty) (*HostInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HostInfo not implemented")
}
func (UnimplementedNetworkServer) EnsureNetwork(context.Context, *EnsureNetworkRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureNetwork not implemented")
}
func (UnimplementedNetworkServer) DestroyNetwork(context.Context, *DestroyNetworkRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyNetwork not implemented")
}
func (UnimplementedNetworkServer) AttachPort(context.Context, *AttachPortRequest) (*AttachPortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachPort not implemented")
}
func (UnimplementedNetworkServer) DetachPort(context.Context, *DetachPortRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachPort not implemented")
}
func (UnimplementedNetworkServer) RotateMeshPeer(context.Context, *RotateMeshPeerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateMeshPeer not implemented")
}
func (UnimplementedNetworkServer) mustEmbedUnimplementedNetworkServer() {}
func (UnimplementedNetworkServer) testEmbeddedByValue()                 {}

// UnsafeNetworkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkServer will
// result in compilation errors.
type UnsafeNetworkServer interface {
	mustEmbedUnimplementedNetworkServer()
}

func RegisterNetworkServer(s grpc.ServiceRegistrar, srv NetworkServer) {
	// If the following call panics, it indicates UnimplementedNetworkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Network_ServiceDesc, srv)
}

func _Network_HostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).HostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_HostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).HostInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_EnsureNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).EnsureNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_EnsureNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).EnsureNetwork(ctx, req.(*EnsureNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_DestroyNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).DestroyNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_DestroyNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).DestroyNetwork(ctx, req.(*DestroyNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_AttachPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).AttachPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_AttachPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).AttachPort(ctx, req.(*AttachPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_DetachPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).DetachPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_DetachPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).DetachPort(ctx, req.(*DetachPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_RotateMeshPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateMeshPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).RotateMeshPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_RotateMeshPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).RotateMeshPeer(ctx, req.(*RotateMeshPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Network_ServiceDesc is the grpc.ServiceDesc for Network service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Network_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weft.driver.v1.Network",
	HandlerType: (*NetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostInfo",
			Handler:    _Network_HostInfo_Handler,
		},
		{
			MethodName: "EnsureNetwork",
			Handler:    _Network_EnsureNetwork_Handler,
		},
		{
			MethodName: "DestroyNetwork",
			Handler:    _Network_DestroyNetwork_Handler,
		},
		{
			MethodName: "AttachPort",
			Handler:    _Network_AttachPort_Handler,
		},
		{
			MethodName: "DetachPort",
			Handler:    _Network_DetachPort_Handler,
		},
		{
			MethodName: "RotateMeshPeer",
			Handler:    _Network_RotateMeshPeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driverpb/driver.proto",
}

const (
	Volume_Name_FullMethodName          = "/weft.driver.v1.Volume/Name"
	Volume_Local_FullMethodName         = "/weft.driver.v1.Volume/Local"
	Volume_HostInfo_FullMethodName      = "/weft.driver.v1.Volume/HostInfo"
	Volume_EnsureVolume_FullMethodName  = "/weft.driver.v1.Volume/EnsureVolume"
	Volume_DestroyVolume_FullMethodName = "/weft.driver.v1.Volume/DestroyVolume"
	Volume_AttachVolume_FullMethodName  = "/weft.driver.v1.Volume/AttachVolume"
	Volume_DetachVolume_FullMethodName  = "/weft.driver.v1.Volume/DetachVolume"
)

// VolumeClient is the client API for Volume service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolumeClient interface {
	Name(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NameResponse, error)
	Local(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LocalResponse, error)
	HostInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostInfoResponse, error)
	EnsureVolume(ctx context.Context, in *EnsureVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DestroyVolume(ctx context.Context, in *DestroyVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AttachVolume(ctx context.Context, in *AttachVolumeRequest, opts ...grpc.CallOption) (*AttachVolumeResponse, error)
	DetachVolume(ctx context.Context, in *DetachVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type volumeClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeClient(cc grpc.ClientConnInterface) VolumeClient {
	return &volumeClient{cc}
}

func (c *volumeClient) Name(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, Volume_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeClient) Local(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LocalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocalResponse)
	err := c.cc.Invoke(ctx, Volume_Local_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeClient) HostInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostInfoResponse)
	err := c.cc.Invoke(ctx, Volume_HostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeClient) EnsureVolume(ctx context.Context, in *EnsureVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Volume_EnsureVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeClient) DestroyVolume(ctx context.Context, in *DestroyVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Volume_DestroyVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeClient) AttachVolume(ctx context.Context, in *AttachVolumeRequest, opts ...grpc.CallOption) (*AttachVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachVolumeResponse)
	err := c.cc.Invoke(ctx, Volume_AttachVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeClient) DetachVolume(ctx context.Context, in *DetachVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Volume_DetachVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeServer is the server API for Volume service.
// All implementations must embed UnimplementedVolumeServer
// for forward compatibility.
type VolumeServer interface {
	Name(context.Context, *emptypb.Empty) (*NameResponse, error)
	Local(context.Context, *emptypb.Empty) (*LocalResponse, error)
	HostInfo(context.Context, *emptypb.Empty) (*HostInfoResponse, error)
	EnsureVolume(context.Context, *EnsureVolumeRequest) (*emptypb.Empty, error)
	DestroyVolume(context.Context, *DestroyVolumeRequest) (*emptypb.Empty, error)
	AttachVolume(context.Context, *AttachVolumeRequest) (*AttachVolumeResponse, error)
	DetachVolume(context.Context, *DetachVolumeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedVolumeServer()
}

// UnimplementedVolumeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolumeServer struct{}

func (UnimplementedVolumeServer) Name(context.Context, *emptypb.Empty) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedVolumeServer) Local(context.Context, *emptypb.Empty) (*LocalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Local not implemented")
}
func (UnimplementedVolumeServer) HostInfo(context.Context, *emptypb.Empty) (*HostInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HostInfo not implemented")
}
func (UnimplementedVolumeServer) EnsureVolume(context.Context, *EnsureVolumeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureVolume not implemented")
}
func (UnimplementedVolumeServer) DestroyVolume(context.Context, *DestroyVolumeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyVolume not implemented")
}
func (UnimplementedVolumeServer) AttachVolume(context.Context, *AttachVolumeRequest) (*AttachVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachVolume not implemented")
}
func (UnimplementedVolumeServer) DetachVolume(context.Context, *DetachVolumeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachVolume not implemented")
}
func (UnimplementedVolumeServer) mustEmbedUnimplementedVolumeServer() {}
func (UnimplementedVolumeServer) testEmbeddedByValue()                {}

// UnsafeVolumeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumeServer will
// result in compilation errors.
type UnsafeVolumeServer interface {
	mustEmbedUnimplementedVolumeServer()
}

func RegisterVolumeServer(s grpc.ServiceRegistrar, srv VolumeServer) {
	// If the following call panics, it indicates UnimplementedVolumeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Volume_ServiceDesc, srv)
}

func _Volume_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Volume_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServer).Name(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Volume_Local_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServer).Local(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Volume_Local_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServer).Local(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Volume_HostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServer).HostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Volume_HostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServer).HostInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Volume_EnsureVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServer).EnsureVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Volume_EnsureVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServer).EnsureVolume(ctx, req.(*EnsureVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Volume_DestroyVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServer).DestroyVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Volume_DestroyVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServer).DestroyVolume(ctx, req.(*DestroyVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Volume_AttachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServer).AttachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Volume_AttachVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServer).AttachVolume(ctx, req.(*AttachVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Volume_DetachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServer).DetachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Volume_DetachVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServer).DetachVolume(ctx, req.(*DetachVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Volume_ServiceDesc is the grpc.ServiceDesc for Volume service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Volume_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weft.driver.v1.Volume",
	HandlerType: (*VolumeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _Volume_Name_Handler,
		},
		{
			MethodName: "Local",
			Handler:    _Volume_Local_Handler,
		},
		{
			MethodName: "HostInfo",
			Handler:    _Volume_HostInfo_Handler,
		},
		{
			MethodName: "EnsureVolume",
			Handler:    _Volume_EnsureVolume_Handler,
		},
		{
			MethodName: "DestroyVolume",
			Handler:    _Volume_DestroyVolume_Handler,
		},
		{
			MethodName: "AttachVolume",
			Handler:    _Volume_AttachVolume_Handler,
		},
		{
			MethodName: "DetachVolume",
			Handler:    _Volume_DetachVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driverpb/driver.proto",
}

const (
	Image_HostInfo_FullMethodName  = "/weft.driver.v1.Image/HostInfo"
	Image_Pull_FullMethodName      = "/weft.driver.v1.Image/Pull"
	Image_LocalPath_FullMethodName = "/weft.driver.v1.Image/LocalPath"
	Image_Delete_FullMethodName    = "/weft.driver.v1.Image/Delete"
	Image_InCache_FullMethodName   = "/weft.driver.v1.Image/InCache"
)

// ImageClient is the client API for Image service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageClient interface {
	HostInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostInfoResponse, error)
	Pull(ctx context.Context, in *RefRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	LocalPath(ctx context.Context, in *RefRequest, opts ...grpc.CallOption) (*LocalPathResponse, error)
	Delete(ctx context.Context, in *RefRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	InCache(ctx context.Context, in *RefRequest, opts ...grpc.CallOption) (*InCacheResponse, error)
}

type imageClient struct {
	cc grpc.ClientConnInterface
}

func NewImageClient(cc grpc.ClientConnInterface) ImageClient {
	return &imageClient{cc}
}

func (c *imageClient) HostInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostInfoResponse)
	err := c.cc.Invoke(ctx, Image_HostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageClient) Pull(ctx context.Context, in *RefRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Image_Pull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageClient) LocalPath(ctx context.Context, in *RefRequest, opts ...grpc.CallOption) (*LocalPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocalPathResponse)
	err := c.cc.Invoke(ctx, Image_LocalPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageClient) Delete(ctx context.Context, in *RefRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Image_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageClient) InCache(ctx context.Context, in *RefRequest, opts ...grpc.CallOption) (*InCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InCacheResponse)
	err := c.cc.Invoke(ctx, Image_InCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageServer is the server API for Image service.
// All implementations must embed UnimplementedImageServer
// for forward compatibility.
type ImageServer interface {
	HostInfo(context.Context, *emptypb.Empty) (*HostInfoResponse, error)
	Pull(context.Context, *RefRequest) (*emptypb.Empty, error)
	LocalPath(context.Context, *RefRequest) (*LocalPathResponse, error)
	Delete(context.Context, *RefRequest) (*emptypb.Empty, error)
	InCache(context.Context, *RefRequest) (*InCacheResponse, error)
	mustEmbedUnimplementedImageServer()
}

// UnimplementedImageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageServer struct{}

func (UnimplementedImageServer) HostInfo(context.Context, *emptypb.Empty) (*HostInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HostInfo not implemented")
}
func (UnimplementedImageServer) Pull(context.Context, *RefRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedImageServer) LocalPath(context.Context, *RefRequest) (*LocalPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LocalPath not implemented")
}
func (UnimplementedImageServer) Delete(context.Context, *RefRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedImageServer) InCache(context.Context, *RefRequest) (*InCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InCache not implemented")
}
func (UnimplementedImageServer) mustEmbedUnimplementedImageServer() {}
func (UnimplementedImageServer) testEmbeddedByValue()               {}

// UnsafeImageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServer will
// result in compilation errors.
type UnsafeImageServer interface {
	mustEmbedUnimplementedImageServer()
}

func RegisterImageServer(s grpc.ServiceRegistrar, srv ImageServer) {
	// If the following call panics, it indicates UnimplementedImageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Image_ServiceDesc, srv)
}

func _Image_HostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServer).HostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Image_HostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServer).HostInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Image_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Image_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServer).Pull(ctx, req.(*RefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Image_LocalPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServer).LocalPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Image_LocalPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServer).LocalPath(ctx, req.(*RefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Image_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Image_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServer).Delete(ctx, req.(*RefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Image_InCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServer).InCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Image_InCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServer).InCache(ctx, req.(*RefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Image_ServiceDesc is the grpc.ServiceDesc for Image service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Image_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weft.driver.v1.Image",
	HandlerType: (*ImageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostInfo",
			Handler:    _Image_HostInfo_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _Image_Pull_Handler,
		},
		{
			MethodName: "LocalPath",
			Handler:    _Image_LocalPath_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Image_Delete_Handler,
		},
		{
			MethodName: "InCache",
			Handler:    _Image_InCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driverpb/driver.proto",
}
